window.MUSIC_DATA = [
    {
        "id" : 95,
        "artist" : "MGMT",
        "album" : "Oracular Spectacular",
        "img" : "media/MGMT/Oracular Spectacular.jpg",
        "spotify" : "https://open.spotify.com/album/6mm1Skz3JE6AXneya9Nyiv?si=-VGzSsPyRmGT8vcCTXrkUA",
        "deezer" : "https://www.deezer.com/en/album/71318",
        "youtube" : "https://music.youtube.com/playlist?list=OLAK5uy_m6DeCpNxvp20bwiydbkxbowGEDKnPxMfI",

    },
    {
        "id": 94,
        "artist":"George Benson",
        "album":"Weekend in L.A.",
        "img":"media/George Benson/Weekend in LA.jpg",
    },
    {"artist":"The Pretty Reckless","album":"Going To Hell","img":"media/The Pretty Reckless/Going To Hell.png"},
    {"artist":"Low Roar","album":"0","img":"media/Low Roar/0.jpg"},
    {
        "id" : 91,
        "artist" : "Gotye",
        "album" : "Making Mirrors",
        "img" : "media/Gotye/Making Mirrors.png",
        "spotify" : "https://open.spotify.com/album/4G2rJNhsKOE6iHgtUqZ0Ye?si=hpaPGhpWQCK6nvLpIJTDig"
    },
    {"id": 90, "artist":"U2","album":"Songs of Innocence","img":"media/U2/Songs of Innocence.jpg"},
    {"artist":"Ghost B.C.","album":"Meliora","img":"media/Ghost/Meliora.jpg"},
    {"artist":"Ghost B.C.","album":"Infestissumam","img":"media/Ghost/Infestissumam.jpg"},
    {"artist":"The Neighbourhood","album":"WIPED OUT!","img":"media/The Neighbourhood/Wiped Out.jpg"},
    {"artist":"The Neighbourhood","album":"I Love You.","img":"media/The Neighbourhood/I Love You.jpg"},
    {"artist":"Eels","album":"Beautiful Freak","img":"media/Eels/Beautiful Freak.jpg"},
    {"artist":"Eels","album":"Shootenanny!","img":"media/Eels/Shootenanny!.jpg"},
    {"artist":"Eels","album":"Daisies Of The Galaxy","img":"media/Eels/Daisies Of The Galaxy.jpg"},
    {"artist":"Eels","album":"Electro-Shock Blues","img":"media/Eels/Electro-Shock Blues.jpg"},
    {"artist":"Prodigy","album":"Invaders Must Die","img":"media/Prodigy/Invaders Must Die.jpg"},
    {"artist":"Prodigy","album":"The Fat Of The Land","img":"media/Prodigy/The Fat Of The Land.jpg"},
    {"artist":"Judas Priest","album":"Painkiller","img":"media/Judas Priest/Painkiller.jpg"},
    {"artist":"Judas Priest","album":"British Steel","img":"media/Judas Priest/British Steel.jpg"},
    {"artist":"Judas Priest","album":"Sin After Sin","img":"media/Judas Priest/Sin After Sin.jpg"},
    {"artist":"Moby","album":"Reprise","img":"media/Moby/Reprise.png"},
    {"artist":"Moby","album":"Play","img":"media/Moby/Play.jpg"},
    {"artist":"Moby","album":"Hotel","img":"media/Moby/Hotel.jpg"},
    {"artist":"Asking Alexandria","album":"From Death to Destiny","img":"media/Asking Alexandria/From Death to Destiny.png"},
    {"artist":"Asking Alexandria","album":"Asking Alexandria","img":"media/Asking Alexandria/Asking Alexandria.jpg"},
    {"artist":"Skillet","album":"Awake","img":"media/Skillet/Awake.jpg"},
    {"id": 70, "artist":"Billy Talent","album":"Dead Silence","img":"media/Billy Talent/Dead Silence.png"},
    {"artist":"Billy Talent","album":"Billy Talent 2","img":"media/Billy Talent/Billy Talent 2.jpg"},
    {"artist":"Arctic Monkeys","album":"Tranquility Base Hotel & Casino","img":"media/Arctic Monkeys/Tranquility Base Hotel & Casino.png"},
    {"artist":"Arctic Monkeys","album":"Whatever People Say I Am, That's What I'm Not","img":"media/Arctic Monkeys/Whatever People Say I Am, That's What I'm Not.jpg"},
    {"artist":"Arctic Monkeys","album":"Favourite Worst Nightmare","img":"media/Arctic Monkeys/Favourite Worst Nightmare.jpg"},
    {"artist":"Arctic Monkeys","album":"AM","img":"media/Arctic Monkeys/AM.png"},
    {"artist":"Linkin Park","album":"Living Things","img":"media/Linkin Park/Living Things.jpg"},
    {"artist":"Linkin Park","album":"Meteora","img":"media/Linkin Park/Meteora.jpg"},
    {"artist":"Linkin Park","album":"Minutes to Midnight","img":"media/Linkin Park/Minutes to Midnight.jpg"},
    {"artist":"Linkin Park","album":"Hybrid Theory","img":"media/Linkin Park/Hybrid Theory.jpg"},
    {"id": 60, "artist":"Imagine Dragons","album":"Continued Silence","img":"media/Imagine Dragons/Continued Silence.jpg"},
    {"artist":"Imagine Dragons","album":"Hell and Silence","img":"media/Imagine Dragons/Hell and Silence.jpg"},
    {"artist":"Imagine Dragons","album":"It's Time","img":"media/Imagine Dragons/It's Time.jpg"},
    {"artist":"Imagine Dragons","album":"Night Visions","img":"media/Imagine Dragons/Night Visions.jpg"},
    {"artist":"Imagine Dragons","album":"Imagine Dragons","img":"media/Imagine Dragons/Imagine Dragons.jpg"},
    {"artist":"ATL","album":"Необратимые Последствия","img":"media/ATL/Необратимые Последствия.png"},
    {"artist":"ATL","album":"Вечный Двигатель","img":"media/ATL/Вечный Двигатель.jpg"},
    {"artist":"ATL","album":"Скальпель","img":"media/ATL/Скальпель.png"},
    {"artist":"ATL","album":"Кривой Эфир","img":"media/ATL/Кривой Эфир.png"},
    {"artist":"Placebo","album":"A Place For Us To Dream","img":"media/Placebo/A Place For Us To Dream.png"},
    {"artist":"Placebo","album":"Meds","img":"media/Placebo/Meds.jpg"},
    {"artist":"Placebo","album":"Sleeping With Ghosts","img":"media/Placebo/Sleeping With Ghosts.jpg"},
    {"artist":"Placebo","album":"Placebo","img":"media/Placebo/Placebo.jpg"},
    {"artist":"Placebo","album":"Battle For The Sun","img":"media/Placebo/Battle For The Sun.jpg"},
    {"artist":"Звери","album":"Лучшие","img":"media/Звери/Лучшие.jpg"},
    {"artist":"Кино","album":"Последний Герой","img":"media/Кино/Последний Герой.jpg"},
    {"artist":"Gorillaz","album":"The Now Now","img":"media/Gorillaz/The Now Now.jpg"},
    {"artist":"Gorillaz","album":"Plastic Beach","img":"media/Gorillaz/Plastic Beach.jpg"},
    {"artist":"Gorillaz","album":"Demon Days","img":"media/Gorillaz/Demon Days.png"},
    {"artist":"Gorillaz","album":"Gorillaz","img":"media/Gorillaz/Gorillaz.png"},
    {"artist":"Muse","album":"Simulation Theory","img":"media/Muse/Simulation Theory.jpg"},
    {"artist":"Muse","album":"Drones","img":"media/Muse/Drones.jpg"},
    {"artist":"Muse","album":"The 2nd Law","img":"media/Muse/The 2nd Law.jpg"},
    {"artist":"Muse","album":"The Resistance","img":"media/Muse/The Resistance.jpg"},
    {"artist":"Muse","album":"Black Holes and Revilations","img":"media/Muse/Black Holes and Revilations.jpg"},
    {"artist":"Muse","album":"Absolution","img":"media/Muse/Absolution.jpg"},
    {"artist":"Muse","album":"Origin of Symmetry","img":"media/Muse/Origin of Symmetry.png"},
    {"artist":"The Killers","album":"Hot Fuss","img":"media/The Killers/Hot Fuss.png"},
    {"artist":"The Killers","album":"Day & Age","img":"media/The Killers/Day & Age.png"},
    {"artist":"The Killers","album":"Battle Born","review":"Мой любимый альбом The Killers. Очень сильный. Несколько треков пронимают до мурашек, а закрывающий так вообще сносит башню начисто.","img":"media/The Killers/Battle Born.png"},
    {"id": 30, "artist":"Carpenter Brut","album":"Trilogy","img":"media/Carpenter Brut/Trilogy.jpg"},
    {"artist":"Дайте Танк (!)","album":"Слова-паразиты","review":"Концептуальная вещь. Не совсем альбом, скорее сказка. Несмотря на остроумность переслушивается очень редко.","img":"media/Дайте танк/Слова-паразиты.jpg"},
    {"artist":"Дайте Танк (!)","album":"Человеко-часы","img":"media/Дайте танк/Человеко-часы.webp"},
    {"artist":"Дайте Танк (!)","album":"На Вырост","review":"Коротенький, всего из трёх песен, но зато каких! Как раз после его выхода мы с Илюшей сходили на концерт Дайте Танк (!) в Питере.","img":"media/Дайте танк/На вырост.webp"},
    {"artist":"Дайте Танк (!)","album":"См. рис. 2","img":"media/Дайте танк/См рис 2.webp"},
    {"artist":"Дайте Танк (!)","album":"См. рис. 1","img":"media/Дайте танк/См рис 1.webp"},
    {"artist":"Дайте Танк (!)","album":"Радио Огонь","img":"media/Дайте танк/Радио огонь.webp"},
    {"artist":"Дайте Танк (!)","album":"Интим","img":"media/Дайте танк/Интим.webp"},
    {"artist":"Дайте Танк (!)","album":"Глаза Бояться","img":"media/Дайте танк/Глаза боятся.webp"},
    {"artist":"Дайте Танк (!)","album":"Сохранить Как","img":"media/Дайте танк/Сохранить как.webp"},
    {"artist":"Дайте Танк (!)","album":"Время Собирать Щебень","img":"media/Дайте танк/Время собирать щебень.webp"},
    {"artist":"Thirty Seconds to Mars","album":"America","review":"Кал.","img":"media/30 stm/America.jpg"},
    {"artist":"Thirty Seconds to Mars","album":"Love, Lust, Faith and Dreams","img":"media/30 stm/Love, Lust, Faith and Dreams.jpg"},
    {"artist":"Thirty Seconds to Mars","album":"This is War","img":"media/30 stm/This is War.jpg"},
    {"artist":"Thirty Seconds to Mars","album":"A Beautiful Lie","img":"media/30 stm/A Beautiful Lie.jpg"},
    {"artist":"Thirty Seconds to Mars","album":"30 Seconds to Mars","img":"media/30 stm/30 Seconds to Mars.jpg"},
    {"artist":"Sum 41","album":"Chuck","img":"media/Sum 41/Chuck.jpg"},
    {"artist":"Sum 41","album":"Screaming Bloody Murder","img":"media/Sum 41/Screaming Bloody Murder.jpg"},
    {"artist":"Sum 41","album":"Order in Decline","img":"media/Sum 41/Order in Decline.png"},
    {"artist":"Sum 41","album":"Does This Look Infected?","img":"media/Sum 41/Does This Look Infected.png"},
    {"id": 10, "artist":"Sum 41","album":"All Killer No Filler","img":"media/Sum 41/All Killer No Filler.jpg"},
    {"artist":"Sum 41","album":"13 Voices","img":"media/Sum 41/13 voices.jpg"},
    {"artist":"Coldplay","album":"Music Of The Spheres","img":"media/Coldplay/Music Of The Spheres.png"},
    {"artist":"Coldplay","album":"A Head Full of Dreams","img":"media/Coldplay/A Head Full of Dreams.png"},
    {"artist":"Coldplay","album":"Ghost Stories","review":"Резко отвергнутый мной после первого прослушивания из-за своей непохожести на другие альбом, который Я в итоге распробовал и искренне полюбил. Ночной и убаюкивающий. Под одну из его песен Танюшка шла к алатрю. Прослушивание за рулём крайне противопоказано.","img":"media/Coldplay/Ghost Stories.png"},
    {"artist":"Coldplay","album":"Viva La Vida or Death and All His Friends","review":"Мой самый любимый альбом Coldplay. Энергичный и мечтательный. Абсолютная классика.","img":"media/Coldplay/Viva La Vida.png"},
    {"artist":"Coldplay","album":"X&Y","review":"Ритмичный, почти танцевальный (насколько это вообще возможно для Coldplay) альбом. Трекам нужно сравнительно меньше времени, чтобы раскачаться, а припевы вызывают физические мурашки. Абсолютная конфетка. Песня 'A Message' несколько лет стояла у меня на будильнике.","img":"media/Coldplay/X&Y.png"},
    {
        "id" : 3,
        "artist" : "Coldplay",
        "album" : "A Rush of Blood to the Head",
        "img" : "media/Coldplay/A Rush Of Blood To The Head.png",
        "spotify" : "https://open.spotify.com/album/4E7bV0pzG0LciBSWTszra6",
        "deezer" : "https://www.deezer.com/en/album/300328",
        "youtube" : "https://www.youtube.com/playlist?list=PLZ9DoO2uX9wU6UFsWRnHBavSMp5dfz0kS",
        "review" : "Шикарный. Необычный, нарушающий привычную математическую симметрию жанра, бодрый, но не слишком. Идеальный плейлист для загруженного дня.",
    },
    {
        "id" : 2,
        "artist" : "Coldplay",
        "album" : "Parachutes",
        "img" : "media/Coldplay/Parachutes.png",
        "spotify" : "https://open.spotify.com/album/6ZG5lRT77aJ3btmArcykra?si=UHL7Bin3T3uWDTK7gMSBtQ",
        "deezer" : "https://www.deezer.com/us/album/301663",
        "youtube" : "https://music.youtube.com/playlist?list=OLAK5uy_mO6LoBQmkXq6ZPyLQ6snqEs_IBlmbZAao",
        "review" : "Чудесный лирический альбом. Спокойный, но играющий на высоких нотах. Один из моих самых любимых.",
    },
    {
        "id" : 1,
        "artist" : "Coldplay",
        "album" : "Mylo Xylito",
        "img" : "media/Coldplay/Mylo Xylito.png",
        "spotify" : "https://open.spotify.com/album/2R7iJz5uaHjLEVnMkloO18?si=ZXI3nbyMQVOeGz-spJrRkg",
        "deezer" : "https://www.deezer.com/en/album/7526706",
        "youtube" : "https://music.youtube.com/playlist?list=OLAK5uy_nOhLNbCFIoEH8QwB_uaej_EaJAktQKplA",
        "review" : "Первый альбом в моей жизни, прослушанный целиком. Искренний и разнообразный. Из него ключом бьёт настоящая человеческая радость."
    }
];