window.MUSIC_DATA = [
    {"artist":"MGMT","album":"Oracular Spectacular","desc":"Ревью в процессе.","img":"media/MGMT/Oracular Spectacular.jpg"},
    {"artist":"George Benson","album":"Weekend in L.A.","desc":"Ревью в процессе.","img":"media/George Benson/Weekend in LA.jpg"},
    {"artist":"The Pretty Reckless","album":"Going To Hell","desc":"Ревью в процессе.","img":"media/The Pretty Reckless/Going To Hell.png"},
    {"artist":"Low Roar","album":"0","desc":"Ревью в процессе.","img":"media/Low Roar/0.jpg"},
    {"artist":"Gotye","album":"Making Mirrors","desc":"Ревью в процессе.","img":"media/Gotye/Making Mirrors.png"},
    {"artist":"U2","album":"Songs of Innocence","desc":"Ревью в процессе.","img":"media/U2/Songs of Innocence.jpg"},
    {"artist":"Ghost B.C.","album":"Meliora","desc":"Ревью в процессе.","img":"media/Ghost/Meliora.jpg"},
    {"artist":"Ghost B.C.","album":"Infestissumam","desc":"Ревью в процессе.","img":"media/Ghost/Infestissumam.jpg"},
    {"artist":"The Neighbourhood","album":"WIPED OUT!","desc":"Ревью в процессе.","img":"media/The Neighbourhood/Wiped Out.jpg"},
    {"artist":"The Neighbourhood","album":"I Love You.","desc":"Ревью в процессе.","img":"media/The Neighbourhood/I Love You.jpg"},
    {"artist":"Eels","album":"Beautiful Freak","desc":"Ревью в процессе.","img":"media/Eels/Beautiful Freak.jpg"},
    {"artist":"Eels","album":"Daisies Of The Galaxy","desc":"Ревью в процессе.","img":"media/Eels/Daisies Of The Galaxy.jpg"},
    {"artist":"Eels","album":"Shootenanny!","desc":"Ревью в процессе.","img":"media/Eels/Shootenanny!.jpg"},
    {"artist":"Eels","album":"Daisies Of The Galaxy","desc":"Ревью в процессе.","img":"media/Eels/Daisies Of The Galaxy.jpg"},
    {"artist":"Eels","album":"Electro-Shock Blues","desc":"Ревью в процессе.","img":"media/Eels/Electro-Shock Blues.jpg"},
    {"artist":"Prodigy","album":"Invaders Must Die","desc":"Ревью в процессе.","img":"media/Prodigy/Invaders Must Die.jpg"},
    {"artist":"Prodigy","album":"The Fat Of The Land","desc":"Ревью в процессе.","img":"media/Prodigy/The Fat Of The Land.jpg"},
    {"artist":"Judas Priest","album":"Painkiller","desc":"Ревью в процессе.","img":"media/Judas Priest/Painkiller.jpg"},
    {"artist":"Judas Priest","album":"British Steel","desc":"Ревью в процессе.","img":"media/Judas Priest/British Steel.jpg"},
    {"artist":"Judas Priest","album":"Sin After Sin","desc":"Ревью в процессе.","img":"media/Judas Priest/Sin After Sin.jpg"},
    {"artist":"Moby","album":"Reprise","desc":"Ревью в процессе.","img":"media/Moby/Reprise.png"},
    {"artist":"Moby","album":"Play","desc":"Ревью в процессе.","img":"media/Moby/Play.jpg"},
    {"artist":"Moby","album":"Hotel","desc":"Ревью в процессе.","img":"media/Moby/Hotel.jpg"},
    {"artist":"Asking Alexandria","album":"From Death to Destiny","desc":"Ревью в процессе.","img":"media/Asking Alexandria/From Death to Destiny.png"},
    {"artist":"Asking Alexandria","album":"Asking Alexandria","desc":"Ревью в процессе.","img":"media/Asking Alexandria/Asking Alexandria.jpg"},
    {"artist":"Skillet","album":"Awake","desc":"Ревью в процессе.","img":"media/Skillet/Awake.jpg"},
    {"artist":"Billy Talent","album":"Dead Silence","desc":"Ревью в процессе.","img":"media/Billy Talent/Dead Silence.png"},
    {"artist":"Billy Talent","album":"Billy Talent 2","desc":"Ревью в процессе.","img":"media/Billy Talent/Billy Talent 2.jpg"},
    {"artist":"Arctic Monkeys","album":"Tranquility Base Hotel & Casino","desc":"Ревью в процессе.","img":"media/Arctic Monkeys/Tranquility Base Hotel & Casino.png"},
    {"artist":"Arctic Monkeys","album":"Whatever People Say I Am, That's What I'm Not","desc":"Ревью в процессе.","img":"media/Arctic Monkeys/Whatever People Say I Am, That's What I'm Not.jpg"},
    {"artist":"Arctic Monkeys","album":"Favourite Worst Nightmare","desc":"Ревью в процессе.","img":"media/Arctic Monkeys/Favourite Worst Nightmare.jpg"},
    {"artist":"Arctic Monkeys","album":"AM","desc":"Ревью в процессе.","img":"media/Arctic Monkeys/AM.png"},
    {"artist":"Linkin Park","album":"Living Things","desc":"Ревью в процессе.","img":"media/Linkin Park/Living Things.jpg"},
    {"artist":"Linkin Park","album":"Meteora","desc":"Ревью в процессе.","img":"media/Linkin Park/Meteora.jpg"},
    {"artist":"Linkin Park","album":"Minutes to Midnight","desc":"Ревью в процессе.","img":"media/Linkin Park/Minutes to Midnight.jpg"},
    {"artist":"Linkin Park","album":"Hybrid Theory","desc":"Ревью в процессе.","img":"media/Linkin Park/Hybrid Theory.jpg"},
    {"artist":"Imagine Dragons","album":"Continued Silence","desc":"Ревью в процессе.","img":"media/Imagine Dragons/Continued Silence.jpg"},
    {"artist":"Imagine Dragons","album":"Hell and Silence","desc":"Ревью в процессе.","img":"media/Imagine Dragons/Hell and Silence.jpg"},
    {"artist":"Imagine Dragons","album":"It's Time","desc":"Ревью в процессе.","img":"media/Imagine Dragons/It's Time.jpg"},
    {"artist":"Imagine Dragons","album":"Night Visions","desc":"Ревью в процессе.","img":"media/Imagine Dragons/Night Visions.jpg"},
    {"artist":"Imagine Dragons","album":"Imagine Dragons","desc":"Ревью в процессе.","img":"media/Imagine Dragons/Imagine Dragons.jpg"},
    {"artist":"ATL","album":"Необратимые Последствия","desc":"Ревью в процессе.","img":"media/ATL/Необратимые Последствия.png"},
    {"artist":"ATL","album":"Вечный Двигатель","desc":"Ревью в процессе.","img":"media/ATL/Вечный Двигатель.jpg"},
    {"artist":"ATL","album":"Скальпель","desc":"Ревью в процессе.","img":"media/ATL/Скальпель.png"},
    {"artist":"ATL","album":"Кривой Эфир","desc":"Ревью в процессе.","img":"media/ATL/Кривой Эфир.png"},
    {"artist":"Placebo","album":"A Place For Us To Dream","desc":"Ревью в процессе.","img":"media/Placebo/A Place For Us To Dream.png"},
    {"artist":"Placebo","album":"Meds","desc":"Ревью в процессе.","img":"media/Placebo/Meds.jpg"},
    {"artist":"Placebo","album":"Sleeping With Ghosts","desc":"Ревью в процессе.","img":"media/Placebo/Sleeping With Ghosts.jpg"},
    {"artist":"Placebo","album":"Placebo","desc":"Ревью в процессе.","img":"media/Placebo/Placebo.jpg"},
    {"artist":"Placebo","album":"Battle For The Sun","desc":"Ревью в процессе.","img":"media/Placebo/Battle For The Sun.jpg"},
    {"artist":"Звери","album":"Лучшие","desc":"Ревью в процессе.","img":"media/Звери/Лучшие.jpg"},
    {"artist":"Кино","album":"Последний Герой","desc":"Ревью в процессе.","img":"media/Кино/Последний Герой.jpg"},
    {"artist":"Gorillaz","album":"The Now Now","desc":"Ревью в процессе.","img":"media/Gorillaz/The Now Now.jpg"},
    {"artist":"Gorillaz","album":"Plastic Beach","desc":"Ревью в процессе.","img":"media/Gorillaz/Plastic Beach.jpg"},
    {"artist":"Gorillaz","album":"Demon Days","desc":"Ревью в процессе.","img":"media/Gorillaz/Demon Days.png"},
    {"artist":"Gorillaz","album":"Gorillaz","desc":"Ревью в процессе.","img":"media/Gorillaz/Gorillaz.png"},
    {"artist":"Muse","album":"Simulation Theory","desc":"Ревью в процессе.","img":"media/Muse/Simulation Theory.jpg"},
    {"artist":"Muse","album":"Drones","desc":"Ревью в процессе.","img":"media/Muse/Drones.jpg"},
    {"artist":"Muse","album":"The 2nd Law","desc":"Ревью в процессе.","img":"media/Muse/The 2nd Law.jpg"},
    {"artist":"Muse","album":"The Resistance","desc":"Ревью в процессе.","img":"media/Muse/The Resistance.jpg"},
    {"artist":"Muse","album":"Black Holes and Revilations","desc":"Ревью в процессе.","img":"media/Muse/Black Holes and Revilations.jpg"},
    {"artist":"Muse","album":"Absolution","desc":"Ревью в процессе.","img":"media/Muse/Absolution.jpg"},
    {"artist":"Muse","album":"Origin of Symmetry","desc":"Ревью в процессе.","img":"media/Muse/Origin of Symmetry.png"},
    {"artist":"The Killers","album":"Hot Fuss","desc":"Ревью в процессе.","img":"media/The Killers/Hot Fuss.png"},
    {"artist":"The Killers","album":"Day & Age","desc":"Ревью в процессе.","img":"media/The Killers/Day & Age.png"},
    {"artist":"The Killers","album":"Battle Born","desc":"Мой любимый альбом The Killers. Очень сильный. Несколько треков пронимают до мурашек, а закрывающий так вообще сносит башню начисто.","img":"media/The Killers/Battle Born.png"},
    {"artist":"Carpenter Brut","album":"Trilogy","desc":"Ревью в процессе.","img":"media/Carpenter Brut/Trilogy.jpg"},
    {"artist":"Дайте Танк (!)","album":"Слова-паразиты","desc":"Концептуальная вещь. Не совсем альбом, скорее сказка. Несмотря на остроумность переслушивается очень редко.","img":"media/Дайте танк/Слова-паразиты.jpg"},
    {"artist":"Дайте Танк (!)","album":"Человеко-часы","desc":"Ревью в процессе.","img":"media/Дайте танк/Человеко-часы.webp"},
    {"artist":"Дайте Танк (!)","album":"На Вырост","desc":"Коротенький, всего из трёх песен, но зато каких! Как раз после его выхода мы с Илюшей сходили на концерт Дайте Танк (!) в Питере.","img":"media/Дайте танк/На вырост.webp"},
    {"artist":"Дайте Танк (!)","album":"См. рис. 2","desc":"Ревью в процессе.","img":"media/Дайте танк/См рис 2.webp"},
    {"artist":"Дайте Танк (!)","album":"См. рис. 1","desc":"Ревью в процессе.","img":"media/Дайте танк/См рис 1.webp"},
    {"artist":"Дайте Танк (!)","album":"Радио Огонь","desc":"Ревью в процессе.","img":"media/Дайте танк/Радио огонь.webp"},
    {"artist":"Дайте Танк (!)","album":"Интим","desc":"Ревью в процессе.","img":"media/Дайте танк/Интим.webp"},
    {"artist":"Дайте Танк (!)","album":"Глаза Бояться","desc":"Ревью в процессе.","img":"media/Дайте танк/Глаза боятся.webp"},
    {"artist":"Дайте Танк (!)","album":"Сохранить Как","desc":"Ревью в процессе.","img":"media/Дайте танк/Сохранить как.webp"},
    {"artist":"Дайте Танк (!)","album":"Время Собирать Щебень","desc":"Ревью в процессе.","img":"media/Дайте танк/Время собирать щебень.webp"},
    {"artist":"Thirty Seconds to Mars","album":"America","desc":"Кал.","img":"media/30 stm/America.jpg"},
    {"artist":"Thirty Seconds to Mars","album":"Love, Lust, Faith and Dreams","desc":"Ревью в процессе.","img":"media/30 stm/Love, Lust, Faith and Dreams.jpg"},
    {"artist":"Thirty Seconds to Mars","album":"This is War","desc":"Ревью в процессе.","img":"media/30 stm/This is War.jpg"},
    {"artist":"Thirty Seconds to Mars","album":"A Beautiful Lie","desc":"Ревью в процессе.","img":"media/30 stm/A Beautiful Lie.jpg"},
    {"artist":"Thirty Seconds to Mars","album":"30 Seconds to Mars","desc":"Ревью в процессе.","img":"media/30 stm/30 Seconds to Mars.jpg"},
    {"artist":"Sum 41","album":"Chuck","desc":"Ревью в процессе.","img":"media/Sum 41/Chuck.jpg"},
    {"artist":"Sum 41","album":"Screaming Bloody Murder","desc":"Ревью в процессе.","img":"media/Sum 41/Screaming Bloody Murder.jpg"},
    {"artist":"Sum 41","album":"Order in Decline","desc":"Ревью в процессе.","img":"media/Sum 41/Order in Decline.png"},
    {"artist":"Sum 41","album":"Does This Look Infected?","desc":"Ревью в процессе.","img":"media/Sum 41/Does This Look Infected.png"},
    {"artist":"Sum 41","album":"All Killer No Filler","desc":"Ревью в процессе.","img":"media/Sum 41/All Killer No Filler.jpg"},
    {"artist":"Sum 41","album":"13 Voices","desc":"Ревью в процессе.","img":"media/Sum 41/13 voices.jpg"},
    {"artist":"Coldplay","album":"Music Of The Spheres","desc":"Ревью в процессе.","img":"media/Coldplay/Music Of The Spheres.png"},
    {"artist":"Coldplay","album":"A Head Full of Dreams","desc":"Ревью в процессе.","img":"media/Coldplay/A Head Full of Dreams.png"},
    {"artist":"Coldplay","album":"Ghost Stories","desc":"Резко отвергнутый мной после первого прослушивания из-за своей непохожести на другие альбом, который Я в итоге распробовал и искренне полюбил. Ночной и убаюкивающий. Под одну из его песен Танюшка шла к алатрю. Прослушивание за рулём крайне противопоказано.","img":"media/Coldplay/Ghost Stories.png"},
    {"artist":"Coldplay","album":"Viva La Vida or Death and All His Friends","desc":"Мой самый любимый альбом Coldplay. Энергичный и мечтательный. Абсолютная классика.","img":"media/Coldplay/Viva La Vida.png"},
    {"artist":"Coldplay","album":"X&Y","desc":"Ритмичный, почти танцевальный (насколько это вообще возможно для Coldplay) альбом. Трекам нужно сравнительно меньше времени, чтобы раскачаться, а припевы вызывают физические мурашки. Абсолютная конфетка. Песня 'A Message' несколько лет стояла у меня на будильнике.","img":"media/Coldplay/X&Y.png"},
    {"artist":"Coldplay","album":"A Rush of Blood to the Head","desc":"Шикарный. Необычный, нарушающий привычную математическую симметрию жанра, бодрый, но не слишком. Идеальный плейлист для загруженного дня.","img":"media/Coldplay/A Rush Of Blood To The Head.png"},
    {"artist":"Coldplay","album":"Parachutes","desc":"Чудесный лирический альбом. Спокойный, но играющий на высоких нотах. Один из моих самых любимых.","img":"media/Coldplay/Parachutes.png"},
    {"artist":"Coldplay","album":"Mylo Xylito","desc":"Первый альбом в моей жизни, прослушанный целиком. Искренний и разнообразный. Из него ключом бьёт настоящая тонкая человеческая радость.","img":"media/Coldplay/Mylo Xylito.png"}
];